#release configuration
#Sun Jun 14 19:24:36 CDT 2026
projectVersionPolicyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.org.scijava\:scripting-java.tag=HEAD
exec.activateProfiles=deploy-to-scijava
pushChanges=false
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.rel.org.scijava\:scripting-java=1.0.1
project.scm.org.scijava\:scripting-java.url=https\://github.com/scijava/scripting-java
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/scijava/scripting-java
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.dev.org.scijava\:scripting-java=1.0.2-SNAPSHOT
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.org.scijava\:scripting-java.connection=scm\:git\:https\://github.com/scijava/scripting-java
scm.tag=scripting-java-1.0.1
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
project.scm.org.scijava\:scripting-java.developerConnection=scm\:git\:git@github.com\:scijava/scripting-java
